version: "3.8"

services:
  # Client
  client:
    build: ./client
    ports:
      - "5173:5173"
    networks:
      - talkback-network
    environment:
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - USERS_SERVICE_URL=${USERS_SERVICE_URL}
      - COMMUNICATION_SOCKET_URL=${COMMUNICATION_SOCKET_URL}
      - GAME_SOCKET_URL=${GAME_SOCKET_URL}
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./client
          target: /usr/src/app
          action: sync

  # Auth
  auth_repository_service:
    build: ./server/auth/auth-repository-service
    ports:
      - "3011:3011"
    networks:
      - talkback-network
    environment:
      - REDIS_URL=${REDIS_URL}
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/auth/auth-repository-service
          target: /usr/src/app
          action: sync

  auth_service:
    build: ./server/auth/auth-service
    ports:
      - "3010:3010"
    networks:
      - talkback-network
    environment:
      - AUTH_REPOSITORY_SERVICE_URL=${AUTH_REPOSITORY_SERVICE_URL}
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/auth/auth-service
          target: /usr/src/app
          action: sync

  # Communication
  communication_gateway_service:
    build: ./server/communication/core/communication-gateway-service
    ports:
      - "3000:3000"
    networks:
      - talkback-network
    environment:
      - CHAT_REPOSITORY_SERVICE_URL=${CHAT_REPOSITORY_SERVICE_URL}
      - REDIS_URL=${REDIS_URL}
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/communication/core/communication-gateway-service
          target: /usr/src/app
          action: sync

  # Chat
  chat_repository_service:
    build: ./server/communication/modules/chat/chat-repository-service
    ports:
      - "3021:3021"
    networks:
      - talkback-network
    environment:
      - REDIS_URL=${REDIS_URL}
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/communication/modules/chat/chat-repository-service
          target: /usr/src/app
          action: sync

  # Game
  game_gateway_service:
    build: ./server/game/core/game-gateway-service
    ports:
      - "3030:3030"
    networks:
      - talkback-network
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/game/core/game-gateway-service
          target: /usr/src/app
          action: sync

  # Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - talkback-network

  # Kafka
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_LISTENERS=${KAFKA_LISTENERS}
      - KAFKA_ADVERTISED_LISTENERS=${KAFKA_ADVERTISED_LISTENERS}
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT}
    networks:
      - talkback-network

  # Redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - talkback-network
    # volumes:
    #   - ./redis/entrypoint.sh:/usr/local/bin/entrypoint.sh
    # entrypoint: ["/usr/local/bin/entrypoint.sh"]

networks:
  talkback-network:
    driver: bridge
