services:
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80" # Expose NGINX on port 80 of the host
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d # Mount custom configuration directory
  #   depends_on:
  #     - auth_server
  #     - game_server
  #     - chat_server
  #     - online_server
  #   networks:
  #     - talkback-network

  game_server:
    build: ./server/game-server
    ports:
      - "3030:3030"
    networks:
      - talkback-network
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/game-server
          target: /usr/src/app
          action: sync

  auth_repository_server:
    build: ./server/auth/auth-repository-service
    ports:
      - "3011:3011"
    networks:
      - talkback-network
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/auth/auth-repository-service
          target: /usr/src/app
          action: sync

  auth_server:
    build: ./server/auth/auth-service
    ports:
      - "3010:3010"
    networks:
      - talkback-network
    environment:
      - AUTH_REPOSITORY_SERVER_URL=http://auth_repository_server:3011/api
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/auth/auth-service
          target: /usr/src/app
          action: sync

  chat_repository_server:
    build: ./server/chat-repository-server
    ports:
      - "3021:3021"
    networks:
      - talkback-network
    environment:
      - CHAT_REPOSITORY_SERVER_URL=http://chat_repository_server:3021/api
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/chat-repository-server
          target: /usr/src/app
          action: sync

  chat_server:
    build: ./server/chat-server
    ports:
      - "3020:3020"
    networks:
      - talkback-network
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/chat-server
          target: /usr/src/app
          action: sync

  online_server:
    build: ./server/online-server
    ports:
      - "3000:3000"
    networks:
      - talkback-network
    environment:
      - CHAT_SERVER_URL=http://chat_server:3020/api
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/online-server
          target: /usr/src/app
          action: sync

  client:
    build: ./client
    ports:
      - "5173:5173"
    networks:
      - talkback-network
    environment:
      - AUTH_SERVER_URL=http://auth_server:3010/api/auth
      - AUTH_SERVER_STATIC_URL=http://auth_server:3010/public
      - USERS_SERVER_URL=http://auth_server:3010/api/users
      - ONLINE_SOCKET_URL=http://online_server:3000
      - GAME_SOCKET_URL=http://game_server:3030
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./client
          target: /usr/src/app
          action: sync

networks:
  talkback-network:
    driver: bridge
