version: "3.8"
services:
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80" # Expose NGINX on port 80 of the host
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d # Mount custom configuration directory
  #   depends_on:
  #     - auth_server
  #     - game_server
  #     - chat_server
  #     - online_server
  #   networks:
  #     - talkback-network

  game_server:
    build: ./TalkBackGameServer
    ports:
      - "3030:3030"
    networks:
      - talkback-network
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./TalkBackGameServer
          target: /usr/src/app
          action: sync

  auth_server:
    build: ./TalkBackAuthServer
    ports:
      - "3010:3010"
    networks:
      - talkback-network
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./TalkBackAuthServer
          target: /usr/src/app
          action: sync

  auth_repository_server:
    build: ./AuthRepositoryServer
    ports:
      - "3011:3011"
    networks:
      - talkback-network
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./AuthRepositoryServer
          target: /usr/src/app
          action: sync

  chat_server:
    build: ./TalkBackChatServer
    ports:
      - "3020:3020"
    networks:
      - talkback-network
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./TalkBackChatServer
          target: /usr/src/app
          action: sync

  online_server:
    build: ./TalkBackOnlineServer
    ports:
      - "3000:3000"
    networks:
      - talkback-network
    environment:
      - CHAT_SERVER_URL=http://chat_server:3020/api
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./TalkBackOnlineServer
          target: /usr/src/app
          action: sync

  client:
    build: ./TalkBackClient
    ports:
      - "5173:5173"
    networks:
      - talkback-network
    environment:
      - CHAT_SERVER_URL=http://chat_server:3020/api
      - AUTH_SERVER_URL=http://auth_server:3010/api/auth
      - AUTH_SERVER_STATIC_URL=http://auth_server:3010/public
      - USERS_SERVER_URL=http://auth_server:3010/api/users
      - ONLINE_SOCKET_URL=http://online_server:3000
      - GAME_SOCKET_URL=http://game_server:3030
      - VITE_GAME_SERVER_STATIC_URL=http://localhost:3030/public
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./TalkBackClient
          target: /usr/src/app
          action: sync

networks:
  talkback-network:
    driver: bridge
