services:
  # Client
  client:
    build: ./client
    ports:
      - "5173:5173"
    networks:
      - playtalk-network
    environment:
      - AUTH_SERVICE_API_URL=${AUTH_SERVICE_API_URL}
      - COMMUNICATION_SOCKET_URL=${COMMUNICATION_SOCKET_URL}
      - GAME_SOCKET_URL=${GAME_SOCKET_URL}
    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client
          target: /usr/src/app
          action: sync

  # Auth
  auth_service:
    build: ./server/auth/auth-service
    ports:
      - "3010:3010"
    networks:
      - playtalk-network
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - INTERNAL_SERVICE_HEADER=${INTERNAL_SERVICE_HEADER}
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/auth/auth-service
          target: /usr/src/app
          action: sync

  #Profile
  profile_service:
    build: ./server/profile/profile-service
    ports:
      - "3040:3040"
    networks:
      - playtalk-network
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - INTERNAL_SERVICE_HEADER=${INTERNAL_SERVICE_HEADER}
    develop:
      watch:
        - path: ./server/profile/profile-service/package.json
          action: rebuild
        - path: ./server/profile/profile-service
          target: /usr/src/app
          action: sync

  # Communication
  communication_gateway_service:
    build: ./server/communication/core/communication-gateway-service
    ports:
      - "3000:3000"
    networks:
      - playtalk-network
    environment:
      - REDIS_URL=${REDIS_URL}
      - AUTH_SERVICE_API_URL=${AUTH_SERVICE_API_URL}
      - CHAT_SERVICE_API_URL=${CHAT_SERVICE_API_URL}
      - JWT_SECRET=${JWT_SECRET}
      - INTERNAL_SERVICE_HEADER=${INTERNAL_SERVICE_HEADER}
    develop:
      watch:
        - path: ./server/communication/core/communication-gateway-service/package.json
          action: rebuild
        - path: ./server/communication/core/communication-gateway-service
          target: /usr/src/app
          action: sync

  # Chat
  chat_service:
    build: ./server/communication/modules/chat/chat-service
    ports:
      - "3020:3020"
    networks:
      - playtalk-network
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
      - INTERNAL_SERVICE_HEADER=${INTERNAL_SERVICE_HEADER}
    develop:
      watch:
        - path: ./server/communication/modules/chat/chat-service/package.json
          action: rebuild
        - path: ./server/communication/modules/chat/chat-service
          target: /usr/src/app
          action: sync

  # Game
  game_gateway_service:
    build: ./server/game/core/game-gateway-service
    ports:
      - "3030:3030"
    networks:
      - playtalk-network
    environment:
      - REDIS_URL=${REDIS_URL}
      - TIC_TAC_TOE_SERVICE_API_URL=${TIC_TAC_TOE_SERVICE_API_URL}
      - TIC_TAC_TOE_REPOSITORY_SERVICE_API_URL=${TIC_TAC_TOE_REPOSITORY_SERVICE_API_URL}
      - AUTH_SERVICE_API_URL=${AUTH_SERVICE_API_URL}
      - JWT_SECRET=${JWT_SECRET}
      - INTERNAL_SERVICE_HEADER=${INTERNAL_SERVICE_HEADER}
    develop:
      watch:
        - path: ./server/game/core/game-gateway-service/package.json
          action: rebuild
        - path: ./server/game/core/game-gateway-service
          target: /usr/src/app
          action: sync

  # Tic Tac Toe
  tic_tac_toe_service:
    build:
      context: ./server/game/modules/tic-tac-toe/tic-tac-toe-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - playtalk-network
    environment:
      - REDIS_URL=${REDIS_URL}
      - TIC_TAC_TOE_REPOSITORY_SERVICE_API_URL=${TIC_TAC_TOE_REPOSITORY_SERVICE_API_URL}
      - INTERNAL_SERVICE_HEADER=${INTERNAL_SERVICE_HEADER}
    develop:
      watch:
        - path: ./server/game/modules/tic-tac-toe/tic-tac-toe-service/tic-tac-toe-service.csproj
          action: rebuild
        - path: ./server/game/modules/tic-tac-toe/tic-tac-toe-service
          target: /usr/src/app
          action: sync

  tic_tac_toe_repository_service:
    build: ./server/game/modules/tic-tac-toe/tic-tac-toe-repository-service
    ports:
      - "8082:8082"
    networks:
      - playtalk-network
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
      - INTERNAL_SERVICE_HEADER=${INTERNAL_SERVICE_HEADER}
    develop:
      watch:
        - path: ./server/game/modules/tic-tac-toe/tic-tac-toe-repository-service/package.json
          action: rebuild
        - path: ./server/game/modules/tic-tac-toe/tic-tac-toe-repository-service
          target: /usr/src/app
          action: sync

  # Redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - playtalk-network

networks:
  playtalk-network:
    driver: bridge
