services:
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80" # Expose NGINX on port 80 of the host
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d # Mount custom configuration directory
  #   depends_on:
  #     - auth_server
  #     - game_server
  #     - chat_server
  #     - online_server
  #   networks:
  #     - talkback-network

  game_gateway_service:
    build: ./server/game/core/game-gateway-service
    ports:
      - "3030:3030"
    networks:
      - talkback-network
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/game/core/game-gateway-service
          target: /usr/src/app
          action: sync

  auth_repository_service:
    build: ./server/auth/auth-repository-service
    ports:
      - "3011:3011"
    networks:
      - talkback-network
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/auth/auth-repository-service
          target: /usr/src/app
          action: sync

  auth_service:
    build: ./server/auth/auth-service
    ports:
      - "3010:3010"
    networks:
      - talkback-network
    environment:
      - AUTH_REPOSITORY_SERVER_URL=http://auth_repository_service:3011/api
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/auth/auth-service
          target: /usr/src/app
          action: sync

  chat_repository_service:
    build: ./server/communication/modules/chat/chat-repository-service
    ports:
      - "3021:3021"
    networks:
      - talkback-network
    environment:
      - CHAT_REPOSITORY_SERVER_URL=http://chat_repository_service:3021/api
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/communication/modules/chat/chat-repository-service
          target: /usr/src/app
          action: sync

  chat_service:
    build: ./server/communication/modules/chat/chat-service
    ports:
      - "3020:3020"
    networks:
      - talkback-network
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/communication/modules/chat/chat-service
          target: /usr/src/app
          action: sync

  communication_gateway_service:
    build: ./server/communication/core/communication-gateway-service
    ports:
      - "3000:3000"
    networks:
      - talkback-network
    environment:
      - CHAT_SERVER_URL=http://chat_service:3020/api
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/communication/core/communication-gateway-service
          target: /usr/src/app
          action: sync

  client:
    build: ./client
    ports:
      - "5173:5173"
    networks:
      - talkback-network
    environment:
      - AUTH_SERVER_URL=http://auth_service:3010/api/auth
      - AUTH_SERVER_STATIC_URL=http://auth_service:3010/public
      - USERS_SERVER_URL=http://auth_service:3010/api/users
      - ONLINE_SOCKET_URL=http://communication_gateway_service:3000
      - GAME_SOCKET_URL=http://game_gateway_service:3030
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./client
          target: /usr/src/app
          action: sync

networks:
  talkback-network:
    driver: bridge
