services:
  # Client
  client:
    build: ./client
    ports:
      - "5173:5173"
    networks:
      - talkback-network
    environment:
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - AUTH_REPOSITORY_SERVICE_URL=${AUTH_REPOSITORY_SERVICE_URL}
      - COMMUNICATION_SOCKET_URL=${COMMUNICATION_SOCKET_URL}
      - GAME_SOCKET_URL=${GAME_SOCKET_URL}
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./client
          target: /usr/src/app
          action: sync

  # Auth
  auth_repository_service:
    build: ./server/auth/auth-repository-service
    ports:
      - "3011:3011"
    networks:
      - talkback-network
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - INTERNAL_SERVICE_HEADER=${INTERNAL_SERVICE_HEADER}
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/auth/auth-repository-service
          target: /usr/src/app
          action: sync

  auth_service:
    build: ./server/auth/auth-service
    ports:
      - "3010:3010"
    networks:
      - talkback-network
    environment:
      - AUTH_REPOSITORY_SERVICE_URL=${AUTH_REPOSITORY_SERVICE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - INTERNAL_SERVICE_HEADER=${INTERNAL_SERVICE_HEADER}
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/auth/auth-service
          target: /usr/src/app
          action: sync

  # Communication
  communication_gateway_service:
    build: ./server/communication/core/communication-gateway-service
    ports:
      - "3000:3000"
    networks:
      - talkback-network
    environment:
      - REDIS_URL=${REDIS_URL}
      - CHAT_REPOSITORY_SERVICE_URL=${CHAT_REPOSITORY_SERVICE_URL}
      - AUTH_REPOSITORY_SERVICE_URL=${AUTH_REPOSITORY_SERVICE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - INTERNAL_SERVICE_HEADER=${INTERNAL_SERVICE_HEADER}
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/communication/core/communication-gateway-service
          target: /usr/src/app
          action: sync

  # Chat
  chat_repository_service:
    build: ./server/communication/modules/chat/chat-repository-service
    ports:
      - "3021:3021"
    networks:
      - talkback-network
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
      - INTERNAL_SERVICE_HEADER=${INTERNAL_SERVICE_HEADER}
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/communication/modules/chat/chat-repository-service
          target: /usr/src/app
          action: sync

  # Game
  game_gateway_service:
    build: ./server/game/core/game-gateway-service
    ports:
      - "3030:3030"
    networks:
      - talkback-network
    environment:
      - REDIS_URL=${REDIS_URL}
      - TIC_TAC_TOE_SERVICE_URL=${TIC_TAC_TOE_SERVICE_URL}
      - TIC_TAC_TOE_REPOSITORY_SERVICE_URL=${TIC_TAC_TOE_REPOSITORY_SERVICE_URL}
      - AUTH_REPOSITORY_SERVICE_URL=${AUTH_REPOSITORY_SERVICE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - INTERNAL_SERVICE_HEADER=${INTERNAL_SERVICE_HEADER}
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/game/core/game-gateway-service
          target: /usr/src/app
          action: sync

  # Tic Tac Toe
  tic_tac_toe_service:
    build: ./server/game/modules/tic-tac-toe/tic-tac-toe-service
    ports:
      - "8080:8080"
    networks:
      - talkback-network
    environment:
      - REDIS_URL=${REDIS_URL}
      - TIC_TAC_TOE_REPOSITORY_SERVICE_URL=${TIC_TAC_TOE_REPOSITORY_SERVICE_URL}
      - INTERNAL_SERVICE_HEADER=${INTERNAL_SERVICE_HEADER}
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/game/modules/tic-tac-toe/tic-tac-toe-service
          target: /app
          action: sync

  tic_tac_toe_repository_service:
    build: ./server/game/modules/tic-tac-toe/tic-tac-toe-repository-service
    ports:
      - "8082:8082"
    networks:
      - talkback-network
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
      - INTERNAL_SERVICE_HEADER=${INTERNAL_SERVICE_HEADER}
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./server/game/modules/tic-tac-toe/tic-tac-toe-repository-service
          target: /usr/src/app
          action: sync

  # Redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - talkback-network

networks:
  talkback-network:
    driver: bridge
