version: "3.4"

services:
  talkbackclient:
    image: talkbackclient
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173
